apiVersion: v1
kind: Service
metadata:
  name: frontend-order-management-service
spec:
  selector:
    app: frontend-order-management
  ports:
    - protocol: TCP
      port: 80 # Expose port 80 on the Service
      targetPort: 5173 # Forward traffic to targetPort 5173
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment # This denotes that it's a Deployment
metadata:
  name: frontend-order-management # Name of the deployment
spec:
  replicas: 1 # 1 Pod will be created.
  selector:
    matchLabels:
      app: frontend-order-management
  template:
    metadata:
      labels:
        app: frontend-order-management
    spec:
      containers:
        - name: frontend-order-management
          imagePullPolicy: Always
          image: ghcr.io/markusmunk/react_frontend_order_management:latest
          ports:
            - containerPort: 5173
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
